### ISSUE TITLE
Timeout web UI changed after upgrading to 2110

### ISSUE THREAD

**Issue by elmarsievers** [centreon/centreon#10394]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

centreon-21.10.0-2.el7.centos.noarch
centreon-auto-discovery-server-21.10.0-3.el7.centos.noarch
centreon-base-config-centreon-engine-21.10.0-2.el7.centos.noarch
centreon-broker-21.10.0-2.el7.x86_64
centreon-broker-cbd-21.10.0-2.el7.x86_64
centreon-broker-cbmod-21.10.0-2.el7.x86_64
centreon-broker-core-21.10.0-2.el7.x86_64
centreon-broker-storage-21.10.0-2.el7.x86_64
centreon-clib-21.10.0-2.el7.x86_64
centreon-common-21.10.0-2.el7.centos.noarch
centreon-connector-21.10.0-2.el7.x86_64
centreon-connector-perl-21.10.0-2.el7.x86_64
centreon-connector-ssh-21.10.0-2.el7.x86_64
centreon-database-21.10.0-2.el7.centos.noarch
centreon-engine-21.10.0-2.el7.x86_64
centreon-engine-daemon-21.10.0-2.el7.x86_64
centreon-engine-extcommands-21.10.0-2.el7.x86_64
centreon-gorgone-21.10.0-3.el7.centos.noarch
centreon-gorgone-centreon-config-21.10.0-3.el7.centos.noarch
centreon-license-manager-21.10.0-1.el7.centos.noarch
centreon-license-manager-common-21.10.0-1.el7.centos.noarch
centreon-perl-libs-21.10.0-2.el7.centos.noarch
centreon-poller-centreon-engine-21.10.0-2.el7.centos.noarch
centreon-pp-manager-21.10.0-2.el7.centos.noarch
centreon-release-21.10-2.el7.centos.noarch
centreon-trap-21.10.0-2.el7.centos.noarch
centreon-web-21.10.0-2.el7.centos.noarch
centreon-widget-engine-status-21.10.0-2.el7.centos.noarch
centreon-widget-global-health-21.10.0-2.el7.centos.noarch
centreon-widget-graph-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-grid-map-21.10.0-2.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-host-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-httploader-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.10.0-2.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-service-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-tactical-overview-21.10.0-2.el7.centos.noarch

***Operating System***

cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

***Browser used***

- [X] Microsoft Edge Chromium

Version:  94.0.992.50

### Description

After upgrading to 2110 the web ui is timing out after a while and you have to relogin.

I am not able to find any configuration of timeout inside UI.

I am not sure if it is a bug or a problem of me finding the configuration.

### Steps to Reproduce
Just keep logged on in centreon, after a while you're logged out. In my opinion it should keep the login until I close the browser.

### Logs

**PHP error logs**

[05-Nov-2021 10:07:02 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

[05-Nov-2021 10:08:02 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

[05-Nov-2021 10:09:03 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

[05-Nov-2021 10:10:03 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

[05-Nov-2021 10:11:03 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

[05-Nov-2021 10:12:03 Europe/Paris] CRITICAL: Invalid Credentials {"context":"[object] (Centreon\\Domain\\Authentication\\Exception\\AuthenticationException(code: 0): Invalid Credentials at /usr/share/centreon/src/Centreon/Domain/Authentication/Exception/AuthenticationException.php:38)"}

**centreon-engine logs (*if needed*)**

[1636103347] [10113] Processing object config file '/etc/centreon-engine/dependencies.cfg'
[1636103347] [10113] Processing object config file '/etc/centreon-engine/connectors.cfg'
[1636103347] [10113] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
[1636103347] [10113] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
[1636103347] [10113] Processing object config file '/etc/centreon-engine/meta_host.cfg'
[1636103347] [10113] Processing object config file '/etc/centreon-engine/meta_services.cfg'
[1636103347] [10113] Reading resource file '/etc/centreon-engine/resource.cfg'
[1636103347] [10113] Warning: Host 'RZ03BK201' has no services associated with it!
[1636103347] [10113] Configuration reloaded, main loop continuing.
[1636103347] [10113] Reload configuration finished.

**centreon-broker logs (*if needed*)**

[2021-11-05T09:40:56.869+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/50-tcp.so' which is already loaded
[2021-11-05T09:40:56.869+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/80-sql.so' which is already loaded
[2021-11-05T09:40:56.869+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/20-storage.so' which is already loaded
[2021-11-05T09:40:56.869+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/15-stats.so' which is already loaded
[2021-11-05T10:09:11.174+01:00] [core] [info] main: configuration update requested
[2021-11-05T10:09:11.175+01:00] [core] [info] /var/log/centreon-broker//central-broker-master.log : log started
[2021-11-05T10:09:11.175+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/50-tcp.so' which is already loaded
[2021-11-05T10:09:11.175+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/80-sql.so' which is already loaded
[2021-11-05T10:09:11.175+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/20-storage.so' which is already loaded
[2021-11-05T10:09:11.175+01:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/15-stats.so' which is already loaded

**centreon gorgone logs for Centreon >= 20.4  (*if needed*)**

2021-11-05 10:10:03 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-11-05 10:11:03 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-11-05 10:11:16 - INFO - [proxy] Pong received from '7'
2021-11-05 10:11:16 - INFO - [proxy] Pong received from '6'
2021-11-05 10:12:03 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-11-05 10:12:16 - INFO - [proxy] Pong received from '6'
2021-11-05 10:12:16 - INFO - [proxy] Pong received from '7'
2021-11-05 10:13:03 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-11-05 10:13:16 - INFO - [proxy] Pong received from '6'
2021-11-05 10:13:16 - INFO - [proxy] Pong received from '7'

**Comment by jeremyit** [comment]
Same issue since 2110 upgrade. No logout in 2104.

**Comment by vhsantos** [comment]
We are having the same problem since the last update.

```
2021-11-07 18:37:50 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
2021-11-07 18:37:50 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0x357b330
2021-11-07 18:37:50 - DEBUG - == Info: Connection 20 seems to be dead!
2021-11-07 18:37:50 - DEBUG - == Info: Closing connection 20
2021-11-07 18:37:50 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#21)
2021-11-07 18:37:50 - DEBUG - == Info:   Trying 127.0.0.1...
2021-11-07 18:37:50 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#21)
2021-11-07 18:37:50 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
Host: 127.0.0.1
Accept: */*
Content-Type: application/json; charset=utf-8
Accept-Type: application/json; charset=utf-8
Content-Length: 68

2021-11-07 18:37:50 - DEBUG - => Send data: {"security":{"credentials":{"password":"centreon","login":"admin"}}}
2021-11-07 18:37:50 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
2021-11-07 18:37:50 - DEBUG - => Recv header: HTTP/1.1 401 Unauthorized
2021-11-07 18:37:50 - DEBUG - => Recv header: Date: Sun, 07 Nov 2021 21:37:50 GMT
2021-11-07 18:37:50 - DEBUG - => Recv header: Server: Apache
2021-11-07 18:37:50 - DEBUG - => Recv header: Cache-Control: no-cache, private
2021-11-07 18:37:50 - DEBUG - => Recv header: Api-Version: 2.0
2021-11-07 18:37:50 - DEBUG - => Recv header: X-Frame-Options: sameorigin
2021-11-07 18:37:50 - DEBUG - => Recv header: Transfer-Encoding: chunked
2021-11-07 18:37:50 - DEBUG - => Recv header: Content-Type: application/json
2021-11-07 18:37:50 - DEBUG - => Recv header: 
2021-11-07 18:37:50 - DEBUG - => Recv data: 2c
{"code":401,"message":"Invalid credentials"}
0

2021-11-07 18:37:50 - DEBUG - == Info: Connection #21 to host 127.0.0.1 left intact
2021-11-07 18:37:50 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
2021-11-07 18:38:50 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
2021-11-07 18:38:50 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0x3577770
2021-11-07 18:38:50 - DEBUG - == Info: Connection 21 seems to be dead!
2021-11-07 18:38:50 - DEBUG - == Info: Closing connection 21
2021-11-07 18:38:50 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#22)
2021-11-07 18:38:50 - DEBUG - == Info:   Trying 127.0.0.1...
2021-11-07 18:38:50 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#22)
2021-11-07 18:38:50 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
Host: 127.0.0.1
Accept: */*
Content-Type: application/json; charset=utf-8
Accept-Type: application/json; charset=utf-8
Content-Length: 68

2021-11-07 18:38:50 - DEBUG - => Send data: {"security":{"credentials":{"password":"centreon","login":"admin"}}}
2021-11-07 18:38:50 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
2021-11-07 18:38:51 - DEBUG - => Recv header: HTTP/1.1 401 Unauthorized
2021-11-07 18:38:51 - DEBUG - => Recv header: Date: Sun, 07 Nov 2021 21:38:51 GMT
2021-11-07 18:38:51 - DEBUG - => Recv header: Server: Apache
2021-11-07 18:38:51 - DEBUG - => Recv header: Cache-Control: no-cache, private
2021-11-07 18:38:51 - DEBUG - => Recv header: Api-Version: 2.0
2021-11-07 18:38:51 - DEBUG - => Recv header: X-Frame-Options: sameorigin
2021-11-07 18:38:51 - DEBUG - => Recv header: Transfer-Encoding: chunked
2021-11-07 18:38:51 - DEBUG - => Recv header: Content-Type: application/json
2021-11-07 18:38:51 - DEBUG - => Recv header: 
2021-11-07 18:38:51 - DEBUG - => Recv data: 2c
{"code":401,"message":"Invalid credentials"}
0

2021-11-07 18:38:51 - DEBUG - == Info: Connection #22 to host 127.0.0.1 left intact
2021-11-07 18:38:51 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
2021-11-07 18:38:59 - INFO - [proxy] Send pings
2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '6' for node '6'
2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '4' for node '4'
2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 6~~6] [data = {}]
2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '3' for node '3'
2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 4~~4] [data = {}]
2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '2' for node '2'
2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '5' for node '5'
2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 5~~5] [data = {}]
2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 2~~2] [data = {}]
2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 3~~3] [data = {}]
2021-11-07 18:38:59 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"4"}}
2021-11-07 18:38:59 - INFO - [proxy] Pong received from '4'
2021-11-07 18:38:59 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"3"}}
2021-11-07 18:39:00 - INFO - [proxy] Pong received from '3'
2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"5"}}
2021-11-07 18:39:00 - INFO - [proxy] Pong received from '5'
2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"2"}}
2021-11-07 18:39:00 - INFO - [proxy] Pong received from '2'
2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"6"}}
2021-11-07 18:39:00 - INFO - [proxy] Pong received from '6'
2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable

```

**Comment by elmarsievers** [comment]
HI,

some more information, why it is so important for our team: We've a monitoring TV without any user sitting before it, just for all from our team to watch at the system environment status.

So if there is a logout happening all xx minutes it is really annoying for us.

Kind Regards

**Comment by jeremyit** [comment]
@elmarsievers  the same for our team  :-/

**Comment by lpinsivy** [comment]
Hi,

Can you h-check the value of session.gc_maxlifetime from /etc/php.d/50-centreon.ini
With default Centreon upgrade you should have:
```
# cat /etc/php.d/50-centreon.ini
max_execution_time = 300
session.use_strict_mode = 1
session.gc_maxlifetime = 7200
expose_php = Off
date.timezone = Europe/Paris
```

**Comment by jeremyit** [comment]
@lpinsivy my file 50-centreon.ini has same values

**Comment by lpinsivy** [comment]
And what is the value of "Sessions Expiration Time" field in "Administration > Parameters > Centreon UI" menu?

**Comment by lpinsivy** [comment]
The date of MariaDB matches the system date?

```
[root@srvt-central-2110 ~]# date
mar. nov.  9 16:43:30 CET 2021
MariaDB [(none)]> SELECT NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2021-11-09 16:43:18 |
+---------------------+
1 row in set (0.000 sec)
```

**Comment by lpinsivy** [comment]
What is your account language in Centreon and what is the Centreon timezone (menu Administration > Parameters > Centreon UI)?

**Comment by jeremyit** [comment]
date of MariaDB matches system date

Centreon timezone is Europe/paris
accoutn language is EN_US with Paris Timezone

**Comment by elmarsievers** [comment]
HI ,

so /etc/php.d/50-centreon.ini was configured like your example. Changed to 13 hours (session.gc_maxlifetime = 46800), but cannot change minutes value in //Sessions Expiration Time" field in "Administration > Parameters > Centreon UI"//.

error message, if I set to 780:
Life duration of sessions. The value in minutes cannot be greater than the session.gc_maxlifetime value set in your php centreon.ini file.

**Comment by jeremyit** [comment]
up! very annoying behavior this timeout ...
How can I help you to resolve issue ?

**Comment by szutman** [comment]
Hello,

Same issue in my installation and this is very burdensome problem for us. Please find solution, because Centreon is our main monitoring solutions and login again sometimes after 10 minutes is very hard problem !!!

**Comment by jeremyit** [comment]
Hi @lpinsivy ,

we use Local authentication

**Comment by lpinsivy** [comment]
@jeremyit do you use also your local account for CLAPI/API commands?

**Comment by lpinsivy** [comment]
@jeremyit and both (Centreon server and DBMS) are synchronized on the same NTP server?

**Comment by jeremyit** [comment]
I have only one Centreon server. All stuffs in one box :)

**Comment by jeremyit** [comment]
It's a physical server sync with NTP pool FR.
I've already check date/hour en that box

**Comment by lpinsivy** [comment]
@jeremyit your account is the 'admin' account?
Do you have Autodiscovery enabled in gorgoned?
```
2021-11-07 18:37:50 - DEBUG - == Info: Connection #21 to host 127.0.0.1 left intact
2021-11-07 18:37:50 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
2021-11-07 18:38:50 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
2021-11-07 18:38:50 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0x3577770
2021-11-07 18:38:50 - DEBUG - == Info: Connection 21 seems to be dead!
2021-11-07 18:38:50 - DEBUG - == Info: Closing connection 21
2021-11-07 18:38:50 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#22)
2021-11-07 18:38:50 - DEBUG - == Info:   Trying 127.0.0.1...
2021-11-07 18:38:50 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#22)
2021-11-07 18:38:50 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
Host: 127.0.0.1
Accept: */*
Content-Type: application/json; charset=utf-8
Accept-Type: application/json; charset=utf-8
Content-Length: 68

2021-11-07 18:38:50 - DEBUG - => Send data: {"security":{"credentials":{"password":"centreon","login":"admin"}}}
```

**Comment by jeremyit** [comment]
No admin is renamed.
Autodiscovery is not used and disable.


2021-12-05 03:35:00 - INFO - [statistics] Collecting Engine statistics from target '2'
2021-12-05 03:35:19 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:36:19 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:37:19 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:38:19 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:39:19 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:40:00 - INFO - [cron] Launching job 'broker_stats'
2021-12-05 03:40:00 - INFO - [cron] Launching job 'engine_stats'
2021-12-05 03:40:00 - INFO - [statistics] Collecting Engine statistics from target '2'
2021-12-05 03:40:20 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:41:20 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:42:20 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:43:20 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:43:30 - INFO - [core] Setcoreid changed 2
2021-12-05 03:44:20 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:45:00 - INFO - [cron] Launching job 'broker_stats'
2021-12-05 03:45:00 - INFO - [cron] Launching job 'engine_stats'
2021-12-05 03:45:00 - INFO - [statistics] Collecting Engine statistics from target '2'
2021-12-05 03:45:21 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:46:21 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:47:21 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:48:21 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-05 03:49:21 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']

**Comment by lpinsivy** [comment]
Internal ticket MON-11884

**Comment by kduret** [comment]
@jeremyit could you try this fix ? https://github.com/centreon/centreon/pull/10493/files

**Comment by jeremyit** [comment]
yes! It's fixed.
thank you

**Comment by elmarsievers** [comment]
its'fixed here too. Great job.

thank you.

happy christmas

**Comment by raufis27** [comment]
I just noticed that since last update I have the same errors and pooler doesn't update. Applied fix provided above but it didn't help. 

`2021-12-23 19:15:00 - INFO - [cron] Launching job 'engine_stats'
2021-12-23 19:15:00 - INFO - [statistics] Collecting Engine statistics from target '1'
2021-12-23 19:15:39 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-23 19:16:40 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-23 19:17:40 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-23 19:18:40 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']
2021-12-23 19:19:41 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '500'] [message: 'Internal Server Error']`

**Comment by grzywak97** [comment]
Hi, 
Same issue after my upgrade. 
I followed by @kduret and it's propably works, but still i can't change session expiration time. I want to change from 120 minutes to 5 days (7200 minutes) We have monitoring team and it's annoying to log in every 2 hours. It is the same problem like @elmarsievers had. I changed session.gc_maxlifetime saved file and I tried to change value. I don't know if I have to do anything else?

**Comment by tizianosartori** [comment]
> @jeremyit could you try this fix ? https://github.com/centreon/centreon/pull/10493/files

this works out for us

**Comment by tizianosartori** [comment]
> 

There is still a problem, now you are able to enter but in some cases you press the login button and the login interface remains waiting, then it unlocks by itself.

**Comment by sako-cmr** [comment]
I have same problem. everyone says it's fixed but i don't understand what it do.

**Comment by govi230** [comment]
> We are having the same problem since the last update.
> 
> ```
> 2021-11-07 18:37:50 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
> 2021-11-07 18:37:50 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0x357b330
> 2021-11-07 18:37:50 - DEBUG - == Info: Connection 20 seems to be dead!
> 2021-11-07 18:37:50 - DEBUG - == Info: Closing connection 20
> 2021-11-07 18:37:50 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#21)
> 2021-11-07 18:37:50 - DEBUG - == Info:   Trying 127.0.0.1...
> 2021-11-07 18:37:50 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#21)
> 2021-11-07 18:37:50 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
> Host: 127.0.0.1
> Accept: */*
> Content-Type: application/json; charset=utf-8
> Accept-Type: application/json; charset=utf-8
> Content-Length: 68
> 
> 2021-11-07 18:37:50 - DEBUG - => Send data: {"security":{"credentials":{"password":"centreon","login":"admin"}}}
> 2021-11-07 18:37:50 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
> 2021-11-07 18:37:50 - DEBUG - => Recv header: HTTP/1.1 401 Unauthorized
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Date: Sun, 07 Nov 2021 21:37:50 GMT
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Server: Apache
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Cache-Control: no-cache, private
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Api-Version: 2.0
> 2021-11-07 18:37:50 - DEBUG - => Recv header: X-Frame-Options: sameorigin
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Transfer-Encoding: chunked
> 2021-11-07 18:37:50 - DEBUG - => Recv header: Content-Type: application/json
> 2021-11-07 18:37:50 - DEBUG - => Recv header: 
> 2021-11-07 18:37:50 - DEBUG - => Recv data: 2c
> {"code":401,"message":"Invalid credentials"}
> 0
> 
> 2021-11-07 18:37:50 - DEBUG - == Info: Connection #21 to host 127.0.0.1 left intact
> 2021-11-07 18:37:50 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
> 2021-11-07 18:38:50 - DEBUG - [autodiscovery] -class- host discovery - check centreon module installed
> 2021-11-07 18:38:50 - DEBUG - == Info: Found bundle for host 127.0.0.1: 0x3577770
> 2021-11-07 18:38:50 - DEBUG - == Info: Connection 21 seems to be dead!
> 2021-11-07 18:38:50 - DEBUG - == Info: Closing connection 21
> 2021-11-07 18:38:50 - DEBUG - == Info: About to connect() to 127.0.0.1 port 80 (#22)
> 2021-11-07 18:38:50 - DEBUG - == Info:   Trying 127.0.0.1...
> 2021-11-07 18:38:50 - DEBUG - == Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#22)
> 2021-11-07 18:38:50 - DEBUG - => Send header: POST /centreon/api/beta/login HTTP/1.1
> Host: 127.0.0.1
> Accept: */*
> Content-Type: application/json; charset=utf-8
> Accept-Type: application/json; charset=utf-8
> Content-Length: 68
> 
> 2021-11-07 18:38:50 - DEBUG - => Send data: {"security":{"credentials":{"password":"centreon","login":"admin"}}}
> 2021-11-07 18:38:50 - DEBUG - == Info: upload completely sent off: 68 out of 68 bytes
> 2021-11-07 18:38:51 - DEBUG - => Recv header: HTTP/1.1 401 Unauthorized
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Date: Sun, 07 Nov 2021 21:38:51 GMT
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Server: Apache
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Cache-Control: no-cache, private
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Api-Version: 2.0
> 2021-11-07 18:38:51 - DEBUG - => Recv header: X-Frame-Options: sameorigin
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Transfer-Encoding: chunked
> 2021-11-07 18:38:51 - DEBUG - => Recv header: Content-Type: application/json
> 2021-11-07 18:38:51 - DEBUG - => Recv header: 
> 2021-11-07 18:38:51 - DEBUG - => Recv data: 2c
> {"code":401,"message":"Invalid credentials"}
> 0
> 
> 2021-11-07 18:38:51 - DEBUG - == Info: Connection #22 to host 127.0.0.1 left intact
> 2021-11-07 18:38:51 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - Login error [code: '401'] [message: 'Unauthorized']
> 2021-11-07 18:38:59 - INFO - [proxy] Send pings
> 2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '6' for node '6'
> 2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '4' for node '4'
> 2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 6~~6] [data = {}]
> 2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '3' for node '3'
> 2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 4~~4] [data = {}]
> 2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '2' for node '2'
> 2021-11-07 18:38:59 - DEBUG - [proxy] choose node target '5' for node '5'
> 2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 5~~5] [data = {}]
> 2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 2~~2] [data = {}]
> 2021-11-07 18:38:59 - DEBUG - [proxy] Send message: [action = PING] [token = ] [target = 3~~3] [data = {}]
> 2021-11-07 18:38:59 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"4"}}
> 2021-11-07 18:38:59 - INFO - [proxy] Pong received from '4'
> 2021-11-07 18:38:59 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
> 2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"3"}}
> 2021-11-07 18:39:00 - INFO - [proxy] Pong received from '3'
> 2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
> 2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"5"}}
> 2021-11-07 18:39:00 - INFO - [proxy] Pong received from '5'
> 2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
> 2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"2"}}
> 2021-11-07 18:39:00 - INFO - [proxy] Pong received from '2'
> 2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
> 2021-11-07 18:39:00 - DEBUG - [core] Message received - [PONG] [] [] {"data":{"id":"6"}}
> 2021-11-07 18:39:00 - INFO - [proxy] Pong received from '6'
> 2021-11-07 18:39:00 - DEBUG - [core] zmq_recvmsg error: Resource temporarily unavailable
> ```

@vhsantos    {"code":401,"message":"Invalid credentials"}    

Same issue I was facing at auto discovery . But I check "/etc/centreon-gorgone/config.d/31-centreon-api.yaml" configuration file then I found that wrong credentials (username and password) was specified for "centreonv2" and "clapi" both. These credential same as that we used to login into centreon UI
After configure correctly restart the gorgoned service with  "systemctl restart gorgoned"
In my case It was working fine
