### ISSUE TITLE
After update of LibZMQ3 to LibZMQ4: problem with centreon-plugin-Virtualization-VMWare-daemon

### ISSUE THREAD

**Issue by o71** [centreon/centreon#5587]
**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**OS**: CES

I can't reinstall 'centreon-plugin-Virtualization-VMWare-daemon.noarch' because of LibZMQ3 does'nt exist now, it's replaced by LibZMQ4.

How can I do to use solve it ?

Thanks

`yum install centreon-plugin-Virtualization-VMWare-daemon.noarch
Modules complémentaires chargés : fastestmirror, security
Configuration du processus d'installation
Loading mirror speeds from cached hostfile
 * base: mirrors.standaloneinstaller.com
 * extras: centos.quelquesmots.fr
 * updates: fr.mirror.babylon.network
Résolution des dépendances
--> Lancement de la transaction de test
---> Package centreon-plugin-Virtualization-VMWare-daemon.noarch 0:2.3.1-2.el6 will be installé
--> Traitement de la dépendance : perl(ZMQ::LibZMQ3) pour le paquet : centreon-plugin-Virtualization-VMWare-daemon-2.3.1-2.el6.n                                    oarch
Le paquet perl-ZMQ-LibZMQ3-1.19-1.el6.x86_64 est rendu obsolète par perl-ZMQ-LibZMQ4-0.01-1.el6.x86_64 qui est déjà installé
--> Résolution des dépendances terminée
Erreur : Paquet : centreon-plugin-Virtualization-VMWare-daemon-2.3.1-2.el6.noarch (centreon-noarch)
             Requiert : perl(ZMQ::LibZMQ3)
             Disponible : perl-ZMQ-LibZMQ3-1.19-1.el6.x86_64 (centreon)
                 perl(ZMQ::LibZMQ3)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest
`

**Comment by Sims24** [comment]
Hi, 

This is a known issue since yesterday, we will publish required packages today to fix the issue. 

In the meantime you can exclude this package from upgrade to avoid this. 

Thanks,

**Comment by Sims24** [comment]
@o71 fix has been pushed online, you should not have the problem anymore

Thanks,

**Comment by o71** [comment]
I have do no update for the moment perhaps with 2.8.12 ?
Thanks

**Comment by zig-lh** [comment]
Hello,

Same for me. 

Thanks.

**Comment by garnier-quentin** [comment]
It should be fixed on repository.

**Comment by Eroso** [comment]
Hi!

I have the same problem when I execute the command : 
_yum clean all & yum -y update_

Result : 

```
Paquet : centreon-plugin-Virtualization-VMWare-daemon-2.3.1-2.el6.noarch (@centreon-noarch)
             Requiert : perl(ZMQ::LibZMQ3)
             Suppression : perl-ZMQ-LibZMQ3-1.19-1.el6.x86_64 (@ces-standard-stable)
                 perl(ZMQ::LibZMQ3)
             Rendu obsolète par : perl-ZMQ-LibZMQ4-0.01-1.el6.x86_64 (centreon)
                 Non trouvé
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

```

Thanks

**Comment by Sims24** [comment]
We've probably met some routing problem between repositories .. So you should erase centreon-plugin-Virtualization-VMWare-daemon-2.3.1-2.el6.noarch  with rpm -e --nodeps xx **BUT** until we put it back online you may use centreon_vmware github to install it waiting for the RPM release : 

- https://github.com/centreon/centreon-vmware/blob/master/doc/en/installation/index.rst#centreon-vmware-installation---centosrhel-6-systems

**Comment by btassite** [comment]
Same issue here, installed Centreon 2.8.3 from CES 3.4.1 ISO on Friday, updated to 2.8.11 (two days ago) and today to 2.8.12, still the same error when trying to install centreon-plugin-Virtualization-VMWare-daemon (can't remove it because it was never installed) with both 2.8.11 and 2.8.12.

**Comment by Sims24** [comment]
Here is the files you should have : 

- centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
- centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20170807-2.el7.noarch

remove all package *plugin* that might have a conflict with. 

We will publish centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch update in the next days in the meantime you can use the workaround through the link above. 

Thanks

**Comment by btassite** [comment]
Will the el7 packages be compatible with CES 3.3/3.4.1 (CentOS 6.8/6.9)?

**Comment by Sims24** [comment]
Yes we publish rpm packages for both

**Comment by lpinsivy** [comment]
@btassite it is now ok for you?

**Comment by btassite** [comment]
Yes, thank you! I haven't tested its functionality yet (long weekend coming up :)) but the package installs fine now.

**Comment by zig-lh** [comment]
Hello,

I need to uninstall ces-plugins-Virtualization-VMWare-client before upgrade (cause LibZMQ3). 
After upgrading, i can't fin anymore this package.
Do you know why?

Thank you.

**Comment by Sims24** [comment]
@zig-lh  Because name has changed. See my answer above : 

centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20170807-2.el7.noarch

**Comment by zig-lh** [comment]
Ok, thank you. 
Is the config same like old plugin?
Because when i update it, all of my services using it are broken:
UNKNOWN: Cannot load module --plugin. Can't locate apps/vmware/connector/plugin.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.\n

**Comment by Sims24** [comment]
@zig-lh use like below : 

/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin

This is the new standard for all centreon-plugin. vmware related check fit this new standard. Seems like we miss something as we did not mention this breaking change in rpm changelog. Sorry about that

**Comment by zig-lh** [comment]
Thanks a lot, i will try it this morning ;)

**Comment by btassite** [comment]
New packages' functionality works here too. FYI, the difference between CES 3.3 and 3.4.1 (Centreon 2.7.x and 2.8.x):

3.3:
$ vmck="/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1"

3.4.1:
$ vmck="/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1"

Then you can run checks for both like this:
$ $vmck --container=foo --mode=getmap
(where foo is a site you configured in /etc/centreon/centreon_vmware.pm)

**Comment by flooll** [comment]
Hi,
I'v got the same error as zig-lh commented on 1 Sep
UNKNOWN: Cannot load module --plugin. Can't locate apps/vmware/connector/plugin.pm in @inc (@inc contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.\n
but, I'dont have the /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl plugin

**Comment by loic45** [comment]
Hi, 

I have the same problem  on a RHEL6 with CES 3.0.1 with update to 2.8.15.

I change the /usr/local/src/centreon-plugins/apps/vmware/connector/custom/connector.pm

use ZMQ::LibZMQ3;

by

use ZMQ::LibZMQ4;

It 's OK ... for me ...

**Comment by lpinsivy** [comment]
Repository Centreon 3.3 (ex CEs 3.0) is no more supported.

Actual repository is 3.4

Regards,
