### ISSUE TITLE
Connection refused to database after upgrade of Centreon 19.10 to 20.04

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#8683]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***
Centreon 20.04

For the RPM based systems
using packages for the installation of centreon

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
```

For the deb based systems

-- Copy/Paste the result of the following command --
```
$ dpkg -l | grep centreon
```
***Operating System***

*CentOS7*

### Description

Hello,
After upgrade of Centreon 19.10 to 20.04 , I have this error 

![image](https://user-images.githubusercontent.com/56160040/80985211-31e63900-8e2f-11ea-971f-3610c7313d9c.png)

![image](https://user-images.githubusercontent.com/56160040/80985319-58a46f80-8e2f-11ea-8bdf-8d484dee0845.png)

Pointed out that the BDD is external to the Central Centreon.
And I don't know why the connection is refused because the error only appears after the upgrade.

The centcore configuration file is /etc/centreon/conf.pm, and I noticed that the gorgon service does not use this file.

So I need help to solve and find the origin of this error and the new BDD configuration file.
### Logs

**PHP error logs**

```
tail -f /var/log/centreon/centcore.log
```
![image](https://user-images.githubusercontent.com/56160040/80984894-c13f1c80-8e2e-11ea-8851-a6269da01756.png)

**Comment by rafaelgesser** [comment]
I have same problem.

**Comment by lpinsivy** [comment]
Hi @IdrissaHilda and @rafaelgesser.

We found a little problem during the upgrade. Can you check the **/etc/centreon/config.d/10-database.yaml** file specially for the password (maybe double incorrect quote around the password).

Once this file is corrected, restart the gorgoned process:

`systemctl restart gorgoned`

Regards,

**Comment by rafaelgesser** [comment]
Hello,

 

My /etc/centreon/config.d/10-database.yaml file is here.

======ORIGINAL FILE=====

database:

  db_configuration:

    dsn: "mysql:host=localhost:3306;dbname=centreon"

    username: "centreon"

    password: "MYPASS"

  db_realtime:

    dsn: "mysql:host=localhost:3306;dbname=centreon_storage"

    username: "centreon"

    password: "MYPASS"

======ORIGINAL FILE=====

 

 

I try as below, but it didn't work 

======TEST FILE=====

database:

  db_configuration:

    dsn: ‘mysql:host=localhost:3306;dbname=centreon’

    username: ‘centreon’

    password: ‘MYPASS’

  db_realtime:

    dsn: ‘mysql:host=localhost:3306;dbname=centreon_storage’

    username: ‘centreon’

    password: ‘MYPASS’

======TEST FILE=====

 

Do you have a sample file?

 

Best regards,


Rafael Gesser

 


m: +55 (48) 99157-7250
e: rafael@gesser.com.br

	

 <https://www.linkedin.com/in/rgesser/>   <https://www.facebook.com/gabrielagessertreinamentos>   <https://www.youtube.com/gabrielagesser>   <https://www.instagram.com/gabrielagesser/>  

	

 

 

De: Laurent Pinsivy <notifications@github.com> 
Enviada em: quinta-feira, 7 de maio de 2020 09:24
Para: centreon/centreon <centreon@noreply.github.com>
Cc: rafaelgesser <RAFAEL@GESSER.COM.BR>; Mention <mention@noreply.github.com>
Assunto: Re: [centreon/centreon] Connection refused to database after upgrade of Centreon 19.10 to 20.04 (#8683)

 

Hi @IdrissaHilda <https://github.com/IdrissaHilda>  and @rafaelgesser <https://github.com/rafaelgesser> .

We found a little problem during the upgrade. Can you check the /etc/centreon/config.d/10-database.yaml file specially for the password (maybe double incorrect quote around the password).

Once this file is corrected, restart the gorgoned process:

systemctl restart gorgoned

Regards,

**Comment by lpinsivy** [comment]
This is an example:

```
database:
  db_configuration:
    dsn: "mysql:host=localhost:3306;dbname=centreon"
    username: "centreon"
    password: "MYPASS"
  db_realtime:
    dsn: "mysql:host=localhost:3306;dbname=centreon_storage"
    username: "centreon"
    password: "MYPASS"
```

**Comment by IdrissaHilda** [comment]
Hello @lpinsivy,
I do the same test as @rafaelgesser, I replaced the double quote with the single quote but the problem persists.

Hilda IDRISSA

**Comment by lpinsivy** [comment]
Can you try to apply dos2unix on this file, then stop and start gorgoned?

**Comment by IdrissaHilda** [comment]
I applied this command `dos2unix 10-database.yaml` but the problem is not solved.

**Comment by rafaelgesser** [comment]
> Can you try to apply dos2unix on this file, then stop and start gorgoned?

Problem is not solved.

**Comment by IdrissaHilda** [comment]
Hi @lpinsivy , I need a solution to resolve my problem it's important. Currently my server is inoperable, even though I've tried everything.

best regard
